# Generated by Django 4.2.30 on 2026-05-06 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_add_one_sided_delete_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectChronology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('source', models.CharField(default='manual', max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(default='funding', max_length=80)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('not_required', 'Not Required')], default='missing', max_length=20)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='project_requirements/')),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('level', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('likely_delayed', 'Likely Delayed'), ('already_delayed', 'Already Delayed')], default='on_track', max_length=30)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('suggested_extension_days', models.PositiveIntegerField(default=0)),
                ('days_remaining', models.IntegerField(blank=True, null=True)),
                ('expected_progress', models.PositiveIntegerField(default=0)),
                ('actual_progress', models.PositiveIntegerField(default=0)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('last_admin_notified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-score', 'project__project_end'],
            },
        ),
        migrations.AddField(
            model_name='extensionrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='myapp.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_risk_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_risk_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_risk_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_risk_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='delay_risk_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='actual_specifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='actual_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='actual_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='date_acquired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='official_receipt',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='supplier_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='supplier_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectequipment',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extensionrequest',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='myapp.proposal'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('task', 'Task'), ('project', 'Project'), ('chat', 'Group Chat'), ('announcement', 'Announcement'), ('budget', 'Budget'), ('proposal', 'Proposal'), ('delay_risk', 'Delay Risk')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='projectriskassessment',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='myapp.project'),
        ),
        migrations.AddField(
            model_name='projectrequirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='myapp.project'),
        ),
        migrations.AddField(
            model_name='projectchronology',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronology', to='myapp.project'),
        ),
        migrations.AddField(
            model_name='projectchronology',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='projectrequirement',
            unique_together={('project', 'name')},
        ),
    ]
