# Generated by Django 4.2.30 on 2026-05-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_projectchronology_projectrequirement_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='idx_audit_timestamp'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='idx_audit_user_time'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['model_name', 'object_id'], name='idx_audit_model_object'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['fund_source', 'fiscal_year'], name='idx_budget_fund_year'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['status', 'fiscal_year'], name='idx_budget_status_year'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['date_allocated'], name='idx_budget_alloc_date'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['budget', 'status'], name='idx_alloc_budget_status'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['equipment_item', 'status'], name='idx_alloc_item_status'),
        ),
        migrations.AddIndex(
            model_name='budgetallocation',
            index=models.Index(fields=['allocation_date'], name='idx_alloc_date'),
        ),
        migrations.AddIndex(
            model_name='extensionrequest',
            index=models.Index(fields=['status', '-date_submitted'], name='idx_ext_status_date'),
        ),
        migrations.AddIndex(
            model_name='extensionrequest',
            index=models.Index(fields=['project', 'status'], name='idx_ext_project_status'),
        ),
        migrations.AddIndex(
            model_name='extensionrequest',
            index=models.Index(fields=['proposal', 'status'], name='idx_ext_proposal_status'),
        ),
        migrations.AddIndex(
            model_name='extensionrequest',
            index=models.Index(fields=['proponent', 'status'], name='idx_ext_proponent_status'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='idx_msg_rec_read_created'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='idx_msg_sender_created'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', 'status', '-timestamp'], name='idx_notif_recv_status_time'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['receiver', '-timestamp'], name='idx_notif_recv_time'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', 'status'], name='idx_notif_category_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_code'], name='idx_proj_code'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'project_end'], name='idx_proj_status_end'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['mun', 'status'], name='idx_proj_mun_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['year', 'program'], name='idx_proj_year_program'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['fund_source', 'year'], name='idx_proj_fund_year'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['budget', 'status'], name='idx_proj_budget_status'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['delay_risk_status', 'delay_risk_score'], name='idx_proj_risk'),
        ),
        migrations.AddIndex(
            model_name='projectchronology',
            index=models.Index(fields=['project', '-event_date'], name='idx_chrono_project_date'),
        ),
        migrations.AddIndex(
            model_name='projectchronology',
            index=models.Index(fields=['source', '-date_created'], name='idx_chrono_source_created'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['project', 'status'], name='idx_pe_project_status'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['budget_allocation', 'status'], name='idx_pe_alloc_status'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['supplier_name'], name='idx_pe_supplier'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['date_acquired'], name='idx_pe_acquired'),
        ),
        migrations.AddIndex(
            model_name='projectequipment',
            index=models.Index(fields=['ownership_status', 'delivery_date'], name='idx_pe_owner_delivery'),
        ),
        migrations.AddIndex(
            model_name='projectrequirement',
            index=models.Index(fields=['project', 'status'], name='idx_req_project_status'),
        ),
        migrations.AddIndex(
            model_name='projectrequirement',
            index=models.Index(fields=['category', 'status'], name='idx_req_category_status'),
        ),
        migrations.AddIndex(
            model_name='projectriskassessment',
            index=models.Index(fields=['level', '-score'], name='idx_risk_level_score'),
        ),
        migrations.AddIndex(
            model_name='projectriskassessment',
            index=models.Index(fields=['last_checked'], name='idx_risk_checked'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['status', 'submission_date'], name='idx_prop_status_date'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['municipality', 'status'], name='idx_prop_mun_status'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['budget', 'status'], name='idx_prop_budget_status'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['processed_by', 'status'], name='idx_prop_proc_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='idx_task_project_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='idx_task_assigned_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_date', 'status'], name='idx_task_due_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'due_date'], name='idx_task_project_due'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='idx_user_role_status'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status', 'date_created'], name='idx_user_status_created'),
        ),
    ]
